distclean:

clean:

test:

all:

install:
	plasmapkg2 -i  pouarwallpaper -t wallpaperplugin -g || plasmapkg2 -u  pouarwallpaper -t wallpaperplugin -g

uninstall:
	plasmapkg2 -r  org.pouar.pouarwp -t wallpaperplugin -g